import { PHC, ServiceId } from './types';

export interface ServiceDefinition {
  id: ServiceId;
  name: string;
  category: string;
  description: string;
  baseCapacityRatio: number; // multiplier for daily capacity
}

export const SERVICES_CONFIG: Record<ServiceId, ServiceDefinition> = {
  opd: {
    id: 'opd',
    name: 'Basic Outpatient Care (OPD)',
    category: 'Primary Consultation',
    description: 'General doctor consultation, triage, routine prescriptions, and basic screening.',
    baseCapacityRatio: 40,
  },
  maternal: {
    id: 'maternal',
    name: 'Maternal & Child Health Care',
    category: 'Reproductive Health',
    description: 'Antenatal care (ANC), basic delivery support, neonatal stabilization, and immunization.',
    baseCapacityRatio: 12,
  },
  diagnostics: {
    id: 'diagnostics',
    name: 'Diagnostic & Lab Services',
    category: 'Clinical Diagnostics',
    description: 'Hematology, rapid diagnostic tests (malaria, dengue, TB), microscopy, and blood glucose tests.',
    baseCapacityRatio: 30,
  },
  emergency: {
    id: 'emergency',
    name: 'Emergency & Trauma Stabilization',
    category: 'Critical Care',
    description: 'Initial acute trauma care, shock stabilization, oxygenation, and pre-referral transport prep.',
    baseCapacityRatio: 15,
  },
  inpatient: {
    id: 'inpatient',
    name: 'Basic Inpatient & Observation Care',
    category: 'Ward Management',
    description: 'Short-stay admission (24-48 hrs) for acute febrile illness, IV fluid management, and post-partum rest.',
    baseCapacityRatio: 1.0,
  },
};

export const INITIAL_PHCS: PHC[] = [
  {
    id: 'phc-rampur',
    code: 'UP-STP-001',
    name: 'PHC Rampur',
    district: 'Sitapur',
    state: 'Uttar Pradesh',
    zone: 'North',
    latitude: 27.5744,
    longitude: 80.6695,
    tier: 'Primary Health Centre',
    lastUpdated: '10 mins ago',
    resources: {
      doctorsTotal: 2,
      doctorsAvailable: 2,
      nursesTotal: 4,
      nursesAvailable: 3,
      techniciansTotal: 1,
      techniciansAvailable: 1, // Demo: starts available, can be simulated as 0
      bedsTotal: 12,
      bedsOccupied: 7,
      diagnosticEquipmentFunctional: true,
      emergencyEquipmentFunctional: true,
      maternalEquipmentFunctional: true,
      generalEquipmentFunctional: true,
      powerGridAvailable: true,
      powerBackupAvailable: true,
      waterSupplyAvailable: true,
      coldChainFunctional: true,
      medicineStockPercentage: 84,
      essentialEmergencyDrugsAvailable: true,
      maternalDrugsAvailable: true,
      diagnosticReagentsAvailable: true,
      dailyPatientLoad: 85,
      operationalConfidenceScore: 94,
      recentDailyUsage: [28, 30, 32, 29, 31, 35, 33],
      currentStockUnits: 260,
    },
  },
  {
    id: 'phc-shivapur',
    code: 'UP-STP-002',
    name: 'PHC Shivapur',
    district: 'Sitapur',
    state: 'Uttar Pradesh',
    zone: 'North',
    latitude: 27.612,
    longitude: 80.745,
    tier: 'Primary Health Centre',
    lastUpdated: '25 mins ago',
    resources: {
      doctorsTotal: 3,
      doctorsAvailable: 3,
      nursesTotal: 5,
      nursesAvailable: 4,
      techniciansTotal: 2,
      techniciansAvailable: 2, // Potential donor for Rampur (11.8 km)
      bedsTotal: 16,
      bedsOccupied: 9,
      diagnosticEquipmentFunctional: true,
      emergencyEquipmentFunctional: true,
      maternalEquipmentFunctional: true,
      generalEquipmentFunctional: true,
      powerGridAvailable: true,
      powerBackupAvailable: true,
      waterSupplyAvailable: true,
      coldChainFunctional: true,
      medicineStockPercentage: 92,
      essentialEmergencyDrugsAvailable: true,
      maternalDrugsAvailable: true,
      diagnosticReagentsAvailable: true,
      dailyPatientLoad: 68,
      operationalConfidenceScore: 96,
      recentDailyUsage: [22, 24, 25, 20, 23, 22, 26],
      currentStockUnits: 340,
    },
  },
  {
    id: 'phc-lakshmipur',
    code: 'UP-LKP-003',
    name: 'PHC Lakshmipur',
    district: 'Lakhimpur Kheri',
    state: 'Uttar Pradesh',
    zone: 'North',
    latitude: 27.945,
    longitude: 80.778,
    tier: 'Primary Health Centre',
    lastUpdated: '40 mins ago',
    resources: {
      doctorsTotal: 2,
      doctorsAvailable: 1,
      nursesTotal: 3,
      nursesAvailable: 2,
      techniciansTotal: 1,
      techniciansAvailable: 1,
      bedsTotal: 10,
      bedsOccupied: 8,
      diagnosticEquipmentFunctional: true,
      emergencyEquipmentFunctional: false, // Limited emergency equipment
      maternalEquipmentFunctional: true,
      generalEquipmentFunctional: true,
      powerGridAvailable: true,
      powerBackupAvailable: false, // Power backup issue
      waterSupplyAvailable: true,
      coldChainFunctional: true,
      medicineStockPercentage: 62,
      essentialEmergencyDrugsAvailable: false,
      maternalDrugsAvailable: true,
      diagnosticReagentsAvailable: true,
      dailyPatientLoad: 92,
      operationalConfidenceScore: 82,
      confidenceAnomalyReason: 'Reported stock levels mismatch recent fever OPD spike volume.',
      recentDailyUsage: [38, 41, 45, 42, 40, 48, 50],
      currentStockUnits: 120, // Stock-out risk!
    },
  },
  {
    id: 'phc-sonapur',
    code: 'AS-KMR-004',
    name: 'PHC Sonapur',
    district: 'Kamrup Metropolitan',
    state: 'Assam',
    zone: 'North-East',
    latitude: 26.115,
    longitude: 91.982,
    tier: 'Community Health Centre',
    lastUpdated: '15 mins ago',
    resources: {
      doctorsTotal: 4,
      doctorsAvailable: 3,
      nursesTotal: 6,
      nursesAvailable: 5,
      techniciansTotal: 2,
      techniciansAvailable: 2,
      bedsTotal: 24,
      bedsOccupied: 18,
      diagnosticEquipmentFunctional: true,
      emergencyEquipmentFunctional: true,
      maternalEquipmentFunctional: true,
      generalEquipmentFunctional: true,
      powerGridAvailable: true,
      powerBackupAvailable: true,
      waterSupplyAvailable: true,
      coldChainFunctional: true,
      medicineStockPercentage: 88,
      essentialEmergencyDrugsAvailable: true,
      maternalDrugsAvailable: true,
      diagnosticReagentsAvailable: true,
      dailyPatientLoad: 110,
      operationalConfidenceScore: 91,
      recentDailyUsage: [35, 36, 34, 38, 37, 40, 39],
      currentStockUnits: 380,
    },
  },
  {
    id: 'phc-devgarh',
    code: 'RJ-RSM-005',
    name: 'PHC Devgarh',
    district: 'Rajsamand',
    state: 'Rajasthan',
    zone: 'West',
    latitude: 25.526,
    longitude: 73.906,
    tier: 'Primary Health Centre',
    lastUpdated: '1 hr ago',
    resources: {
      doctorsTotal: 2,
      doctorsAvailable: 1,
      nursesTotal: 3,
      nursesAvailable: 1, // Short staffed nurses
      techniciansTotal: 1,
      techniciansAvailable: 0, // No technician
      bedsTotal: 10,
      bedsOccupied: 5,
      diagnosticEquipmentFunctional: true,
      emergencyEquipmentFunctional: true,
      maternalEquipmentFunctional: false,
      generalEquipmentFunctional: true,
      powerGridAvailable: true,
      powerBackupAvailable: true,
      waterSupplyAvailable: false,
      coldChainFunctional: true,
      medicineStockPercentage: 45,
      essentialEmergencyDrugsAvailable: false,
      maternalDrugsAvailable: false,
      diagnosticReagentsAvailable: false,
      dailyPatientLoad: 75,
      operationalConfidenceScore: 78,
      confidenceAnomalyReason: 'Delayed biometric logs and offline ledger sync pending.',
      recentDailyUsage: [25, 26, 28, 24, 27, 30, 29],
      currentStockUnits: 80,
    },
  },
  {
    id: 'phc-kalyanpur',
    code: 'MH-THN-006',
    name: 'PHC Kalyanpur',
    district: 'Thane',
    state: 'Maharashtra',
    zone: 'West',
    latitude: 19.243,
    longitude: 73.135,
    tier: 'Primary Health Centre',
    lastUpdated: '5 mins ago',
    resources: {
      doctorsTotal: 3,
      doctorsAvailable: 3,
      nursesTotal: 5,
      nursesAvailable: 5,
      techniciansTotal: 2,
      techniciansAvailable: 2,
      bedsTotal: 20,
      bedsOccupied: 14,
      diagnosticEquipmentFunctional: true,
      emergencyEquipmentFunctional: true,
      maternalEquipmentFunctional: true,
      generalEquipmentFunctional: true,
      powerGridAvailable: true,
      powerBackupAvailable: true,
      waterSupplyAvailable: true,
      coldChainFunctional: true,
      medicineStockPercentage: 95,
      essentialEmergencyDrugsAvailable: true,
      maternalDrugsAvailable: true,
      diagnosticReagentsAvailable: true,
      dailyPatientLoad: 125,
      operationalConfidenceScore: 98,
      recentDailyUsage: [45, 48, 50, 47, 52, 51, 49],
      currentStockUnits: 490,
    },
  },
  {
    id: 'phc-borpeta',
    code: 'AS-BRP-007',
    name: 'PHC Borpeta',
    district: 'Barpeta',
    state: 'Assam',
    zone: 'North-East',
    latitude: 26.321,
    longitude: 91.005,
    tier: 'Primary Health Centre',
    lastUpdated: '32 mins ago',
    resources: {
      doctorsTotal: 2,
      doctorsAvailable: 1,
      nursesTotal: 4,
      nursesAvailable: 3,
      techniciansTotal: 1,
      techniciansAvailable: 1,
      bedsTotal: 12,
      bedsOccupied: 6,
      diagnosticEquipmentFunctional: false, // Broken machine
      emergencyEquipmentFunctional: true,
      maternalEquipmentFunctional: true,
      generalEquipmentFunctional: true,
      powerGridAvailable: false, // Grid outage
      powerBackupAvailable: true,
      waterSupplyAvailable: true,
      coldChainFunctional: true,
      medicineStockPercentage: 70,
      essentialEmergencyDrugsAvailable: true,
      maternalDrugsAvailable: true,
      diagnosticReagentsAvailable: false,
      dailyPatientLoad: 80,
      operationalConfidenceScore: 86,
      recentDailyUsage: [25, 26, 27, 26, 28, 29, 31],
      currentStockUnits: 190,
    },
  },
  {
    id: 'phc-nandgaon',
    code: 'MH-NSK-008',
    name: 'PHC Nandgaon',
    district: 'Nashik',
    state: 'Maharashtra',
    zone: 'West',
    latitude: 20.312,
    longitude: 74.659,
    tier: 'Primary Health Centre',
    lastUpdated: '18 mins ago',
    resources: {
      doctorsTotal: 2,
      doctorsAvailable: 2,
      nursesTotal: 4,
      nursesAvailable: 3,
      techniciansTotal: 1,
      techniciansAvailable: 1,
      bedsTotal: 14,
      bedsOccupied: 9,
      diagnosticEquipmentFunctional: true,
      emergencyEquipmentFunctional: true,
      maternalEquipmentFunctional: true,
      generalEquipmentFunctional: true,
      powerGridAvailable: true,
      powerBackupAvailable: true,
      waterSupplyAvailable: true,
      coldChainFunctional: true,
      medicineStockPercentage: 79,
      essentialEmergencyDrugsAvailable: true,
      maternalDrugsAvailable: true,
      diagnosticReagentsAvailable: true,
      dailyPatientLoad: 90,
      operationalConfidenceScore: 92,
      recentDailyUsage: [30, 32, 29, 33, 31, 35, 34],
      currentStockUnits: 250,
    },
  },
  {
    id: 'phc-chandipur',
    code: 'OD-BLS-009',
    name: 'PHC Chandipur',
    district: 'Baleswar',
    state: 'Odisha',
    zone: 'East',
    latitude: 21.468,
    longitude: 87.014,
    tier: 'Primary Health Centre',
    lastUpdated: '45 mins ago',
    resources: {
      doctorsTotal: 2,
      doctorsAvailable: 2,
      nursesTotal: 3,
      nursesAvailable: 2,
      techniciansTotal: 1,
      techniciansAvailable: 1,
      bedsTotal: 12,
      bedsOccupied: 7,
      diagnosticEquipmentFunctional: true,
      emergencyEquipmentFunctional: true,
      maternalEquipmentFunctional: true,
      generalEquipmentFunctional: true,
      powerGridAvailable: true,
      powerBackupAvailable: true,
      waterSupplyAvailable: true,
      coldChainFunctional: true,
      medicineStockPercentage: 81,
      essentialEmergencyDrugsAvailable: true,
      maternalDrugsAvailable: true,
      diagnosticReagentsAvailable: true,
      dailyPatientLoad: 78,
      operationalConfidenceScore: 89,
      recentDailyUsage: [24, 26, 25, 28, 27, 29, 30],
      currentStockUnits: 230,
    },
  },
  {
    id: 'phc-haripur',
    code: 'OD-CTC-010',
    name: 'PHC Haripur',
    district: 'Cuttack',
    state: 'Odisha',
    zone: 'East',
    latitude: 20.463,
    longitude: 85.883,
    tier: 'Primary Health Centre',
    lastUpdated: '12 mins ago',
    resources: {
      doctorsTotal: 3,
      doctorsAvailable: 2,
      nursesTotal: 4,
      nursesAvailable: 4,
      techniciansTotal: 2,
      techniciansAvailable: 1,
      bedsTotal: 18,
      bedsOccupied: 12,
      diagnosticEquipmentFunctional: true,
      emergencyEquipmentFunctional: true,
      maternalEquipmentFunctional: true,
      generalEquipmentFunctional: true,
      powerGridAvailable: true,
      powerBackupAvailable: true,
      waterSupplyAvailable: true,
      coldChainFunctional: true,
      medicineStockPercentage: 85,
      essentialEmergencyDrugsAvailable: true,
      maternalDrugsAvailable: true,
      diagnosticReagentsAvailable: true,
      dailyPatientLoad: 95,
      operationalConfidenceScore: 95,
      recentDailyUsage: [32, 34, 30, 35, 33, 36, 38],
      currentStockUnits: 310,
    },
  },
  {
    id: 'phc-rajapur',
    code: 'MH-RTG-011',
    name: 'PHC Rajapur',
    district: 'Ratnagiri',
    state: 'Maharashtra',
    zone: 'West',
    latitude: 16.657,
    longitude: 73.518,
    tier: 'Primary Health Centre',
    lastUpdated: '22 mins ago',
    resources: {
      doctorsTotal: 2,
      doctorsAvailable: 1,
      nursesTotal: 3,
      nursesAvailable: 2,
      techniciansTotal: 1,
      techniciansAvailable: 0, // No technician
      bedsTotal: 10,
      bedsOccupied: 6,
      diagnosticEquipmentFunctional: true,
      emergencyEquipmentFunctional: true,
      maternalEquipmentFunctional: true,
      generalEquipmentFunctional: true,
      powerGridAvailable: true,
      powerBackupAvailable: true,
      waterSupplyAvailable: true,
      coldChainFunctional: true,
      medicineStockPercentage: 66,
      essentialEmergencyDrugsAvailable: true,
      maternalDrugsAvailable: true,
      diagnosticReagentsAvailable: true,
      dailyPatientLoad: 65,
      operationalConfidenceScore: 84,
      recentDailyUsage: [20, 22, 21, 23, 25, 24, 26],
      currentStockUnits: 140,
    },
  },
  {
    id: 'phc-durgapur',
    code: 'WB-PBD-012',
    name: 'PHC Durgapur',
    district: 'Paschim Bardhaman',
    state: 'West Bengal',
    zone: 'East',
    latitude: 23.520,
    longitude: 87.311,
    tier: 'Community Health Centre',
    lastUpdated: '8 mins ago',
    resources: {
      doctorsTotal: 4,
      doctorsAvailable: 4,
      nursesTotal: 6,
      nursesAvailable: 5,
      techniciansTotal: 2,
      techniciansAvailable: 2,
      bedsTotal: 25,
      bedsOccupied: 19,
      diagnosticEquipmentFunctional: true,
      emergencyEquipmentFunctional: true,
      maternalEquipmentFunctional: true,
      generalEquipmentFunctional: true,
      powerGridAvailable: true,
      powerBackupAvailable: true,
      waterSupplyAvailable: true,
      coldChainFunctional: true,
      medicineStockPercentage: 90,
      essentialEmergencyDrugsAvailable: true,
      maternalDrugsAvailable: true,
      diagnosticReagentsAvailable: true,
      dailyPatientLoad: 130,
      operationalConfidenceScore: 97,
      recentDailyUsage: [44, 46, 49, 45, 47, 50, 48],
      currentStockUnits: 460,
    },
  },
  {
    id: 'phc-sitapur',
    code: 'UP-STP-013',
    name: 'PHC Sitapur Urban',
    district: 'Sitapur',
    state: 'Uttar Pradesh',
    zone: 'North',
    latitude: 27.568,
    longitude: 80.682,
    tier: 'Community Health Centre',
    lastUpdated: '14 mins ago',
    resources: {
      doctorsTotal: 5,
      doctorsAvailable: 4,
      nursesTotal: 8,
      nursesAvailable: 7,
      techniciansTotal: 3,
      techniciansAvailable: 3, // Excellent donor capability (5.2 km from Rampur)
      bedsTotal: 30,
      bedsOccupied: 20,
      diagnosticEquipmentFunctional: true,
      emergencyEquipmentFunctional: true,
      maternalEquipmentFunctional: true,
      generalEquipmentFunctional: true,
      powerGridAvailable: true,
      powerBackupAvailable: true,
      waterSupplyAvailable: true,
      coldChainFunctional: true,
      medicineStockPercentage: 94,
      essentialEmergencyDrugsAvailable: true,
      maternalDrugsAvailable: true,
      diagnosticReagentsAvailable: true,
      dailyPatientLoad: 160,
      operationalConfidenceScore: 99,
      recentDailyUsage: [55, 60, 58, 62, 65, 59, 64],
      currentStockUnits: 620,
    },
  },
  {
    id: 'phc-madhupur',
    code: 'JH-DGH-014',
    name: 'PHC Madhupur',
    district: 'Deoghar',
    state: 'Jharkhand',
    zone: 'East',
    latitude: 24.263,
    longitude: 86.643,
    tier: 'Primary Health Centre',
    lastUpdated: '50 mins ago',
    resources: {
      doctorsTotal: 2,
      doctorsAvailable: 1,
      nursesTotal: 3,
      nursesAvailable: 2,
      techniciansTotal: 1,
      techniciansAvailable: 1,
      bedsTotal: 12,
      bedsOccupied: 9,
      diagnosticEquipmentFunctional: true,
      emergencyEquipmentFunctional: false, // Defibrillator / suction down
      maternalEquipmentFunctional: true,
      generalEquipmentFunctional: true,
      powerGridAvailable: true,
      powerBackupAvailable: true,
      waterSupplyAvailable: true,
      coldChainFunctional: true,
      medicineStockPercentage: 58,
      essentialEmergencyDrugsAvailable: false,
      maternalDrugsAvailable: true,
      diagnosticReagentsAvailable: true,
      dailyPatientLoad: 82,
      operationalConfidenceScore: 80,
      confidenceAnomalyReason: 'Paper register discrepancy reported during last audit cycle.',
      recentDailyUsage: [28, 30, 31, 33, 29, 35, 34],
      currentStockUnits: 110,
    },
  },
  {
    id: 'phc-bilaspur',
    code: 'CG-BSP-015',
    name: 'PHC Bilaspur Rural',
    district: 'Bilaspur',
    state: 'Chhattisgarh',
    zone: 'Central',
    latitude: 22.079,
    longitude: 82.140,
    tier: 'Primary Health Centre',
    lastUpdated: '20 mins ago',
    resources: {
      doctorsTotal: 3,
      doctorsAvailable: 2,
      nursesTotal: 4,
      nursesAvailable: 4,
      techniciansTotal: 2,
      techniciansAvailable: 1,
      bedsTotal: 16,
      bedsOccupied: 10,
      diagnosticEquipmentFunctional: true,
      emergencyEquipmentFunctional: true,
      maternalEquipmentFunctional: true,
      generalEquipmentFunctional: true,
      powerGridAvailable: true,
      powerBackupAvailable: true,
      waterSupplyAvailable: true,
      coldChainFunctional: true,
      medicineStockPercentage: 86,
      essentialEmergencyDrugsAvailable: true,
      maternalDrugsAvailable: true,
      diagnosticReagentsAvailable: true,
      dailyPatientLoad: 98,
      operationalConfidenceScore: 93,
      recentDailyUsage: [34, 35, 37, 36, 38, 39, 41],
      currentStockUnits: 320,
    },
  },
];
